require "app.raceLogic.cRaceLogicBase"
require "app.raceLogic.cRaceLogicManager"
require "app.raceLogic.cRaceModeFree"
require "app.raceLogic.cRaceModeRank"
require "app.raceLogic.cRaceModeCollection"
require "app.raceLogic.cRaceModeEliminate"
require "app.raceLogic.cRaceModeSpeed"
require "app.raceLogic.cRaceModeRank"